/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
  docs: [],
  api: [
    'api/overview',
    {
      type: 'category',
      label: 'Rooms',
      collapsed: false,
      items: ['api/rooms/add', 'api/rooms/delete'],
    },
    {
      type: 'category',
      label: 'Users',
      collapsed: false,
      items: ['api/users/add', 'api/users/delete'],
    },
    {
      type: 'category',
      label: 'Recordings',
      collapsed: false,
      items: ['api/recordings/get', 'api/recordings/delete'],
    },
  ],
  android_sdk: [
    'android_sdk/getting_started',
    'android_sdk/initializing_sdk',
    'android_sdk/activity_result',
    'android_sdk/addons',
    {
      type: 'category',
      label: 'Changelogs',
      collapsed: false,
      items: ['android_sdk/changelogs/v0_2_5', 'android_sdk/changelogs/v0_2_4'],
    },
  ],
};

module.exports = sidebars;
